"""empty message

Revision ID: 5ca44d5571c9
Revises: 129a2b5530e4
Create Date: 2020-10-07 18:38:46.043691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca44d5571c9'
down_revision = '129a2b5530e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('memo', table_name='hd_user_base')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('memo', 'hd_user_base', ['memo'], unique=True)
    # ### end Alembic commands ###
