"""empty message

Revision ID: efdaba1b337f
Revises: 
Create Date: 2020-10-07 17:46:11.810194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdaba1b337f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hd_user_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('user_role', sa.String(length=32), nullable=False),
    sa.Column('level_cd', sa.String(length=2), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('reg_id', sa.String(length=512), nullable=True),
    sa.Column('reg_datetime', sa.DateTime(), nullable=True),
    sa.Column('modify_id', sa.String(length=512), nullable=True),
    sa.Column('modify_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('memo'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hd_user_base')
    # ### end Alembic commands ###
